// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using SB.Domain.Entities.Common;

namespace SB.Domain.Entities.Orders
{
    public partial class OrderHeader:BaseEntity
    {
        public OrderHeader()
        {
            //OrderDetails = new HashSet<OrderDetail>();
        }

        //public int OrderHeaderId { get; set; }
        public string OrderNumber { get; set; }
    
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerAddressId { get; set; }
        public string Note { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal NetAmount { get; set; }
        public DateTime? DocDate { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}