// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SB.Domain.Entities.Orders;

namespace SB.Persistence.Context.Configurations
{
    public partial class OrderHeaderConfiguration : IEntityTypeConfiguration<OrderHeader>
    {
        public void Configure(EntityTypeBuilder<OrderHeader> entity)
        {
            entity.ToTable("OrderHeader");

            entity.Property(x => x.Id).HasColumnName("OrderHeaderId");

            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(25);

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.CustomerAddressId).HasMaxLength(25);

            entity.Property(e => e.CustomerCode)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.CustomerEmail).HasMaxLength(100);

            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.CustomerPhone)
                .IsRequired()
                .HasMaxLength(13);

            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.DocDate).HasColumnType("date");

      

            entity.Property(e => e.NetAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.Note).HasMaxLength(500);

            entity.Property(e => e.OrderNumber)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.StatusId).HasDefaultValueSql("((1))");

            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 5)");

            entity.Property(e => e.UpdatedBy).HasMaxLength(25);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderHeader> entity);
    }
}
